name: Test Endor PR comments
on:
  push:
    branches:
      - test  # Change this to the branch you want to trigger the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Endor Labs SCA Security
        if: github.event_name == 'pull_request'
        uses: endorlabs/github-action@main
        env: 
          ENDOR_SCAN_PR: false
          ENDOR_SCAN_GITHUB: true
        with:
          namespace: tej-learn
          api: "https://api.endorlabs.com"
          enable_github_action_token: true
          enable_pr_comments: true
          scan_dependencies: true
          scan_git_logs: true
          pr: true
          github_token: ${{ secrets.GH_PR_TOKEN }}
          scan_summary_output_type: table
